import {
  CalendarClock,
  CheckCircle2,
  ClipboardList,
  FilePenLine,
  History,
  Search,
  Sparkles,
} from "lucide-react";
import { useSelector } from "react-redux";

const tools = [
  { name: "search_hcp", label: "Search HCP", icon: Search },
  { name: "log_interaction", label: "Log Interaction", icon: ClipboardList },
  { name: "edit_interaction", label: "Edit Interaction", icon: FilePenLine },
  { name: "suggest_next_best_action", label: "Next Best Action", icon: Sparkles },
  { name: "schedule_follow_up", label: "Schedule Follow-up", icon: CalendarClock },
  { name: "summarize_hcp_history", label: "Summarize History", icon: History },
];

export default function ToolPanel() {
  const { toolEvents, suggestions } = useSelector((state) => state.crm);
  const activeToolNames = new Set(toolEvents.map((event) => event.name));

  return (
    <section className="work-panel">
      <div className="compact-heading">
        <div>
          <p className="eyebrow">LangGraph</p>
          <h2>Agent tools</h2>
        </div>
        <CheckCircle2 size={18} />
      </div>

      <div className="tool-grid">
        {tools.map((tool) => {
          const Icon = tool.icon;
          return (
            <span
              className={`tool-chip ${activeToolNames.has(tool.name) ? "active" : ""}`}
              key={tool.name}
            >
              <Icon size={14} />
              {tool.label}
            </span>
          );
        })}
      </div>

      <div className="event-log">
        <h3>Latest tool events</h3>
        {toolEvents.length === 0 ? (
          <p className="muted">Tool calls will appear here after a form submit or chat prompt.</p>
        ) : (
          toolEvents.map((event, index) => (
            <div className="event-row" key={`${event.name}-${index}`}>
              <strong>{event.name.replaceAll("_", " ")}</strong>
              <span>{event.status}</span>
            </div>
          ))
        )}
      </div>

      <div className="suggestion-list">
        <h3>Next-step suggestions</h3>
        {suggestions.length === 0 ? (
          <p className="muted">Suggestions generated by the agent will be shown here.</p>
        ) : (
          suggestions.map((suggestion) => <p key={suggestion}>{suggestion}</p>)
        )}
      </div>
    </section>
  );
}
